source 'https://rubygems.org'

gem 'rails', '4.2.1'
gem 'rails-api'
gem 'spring', :group => :development
gem 'pg'
gem 'thin'
gem 'rack-cors', :require => 'rack/cors'

group :development, :test do
  gem 'pry-rails'
  gem 'pry-byebug'
end